[package]
name = "srf_filter"
version = "0.1.0"
authors = ["Christer Sandberg <christer.sandberg@svt.se>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
cairo-rs = { version = "0.22", default-features = false }
cairo-sys-rs = "0.22"
libc = "0.2"
protobuf = "2.12.0"
regex = "1"

[profile.release]
panic = 'abort'
